<?php
$cards[1]='<a href="/global/tvchile.php" class="spriteglobal sprite-tvchile TV Chile"></a>&nbsp;<a href="/global/lared.php" class="spriteglobal sprite-laredchile La Red"></a>&nbsp;<a href="/global/mega.php" class="spriteglobal sprite-megachile Mega"></a><br><a href="/global/canal13c.php" class="spriteglobal sprite-canal13c Canal 13 Chile"></a><a href="/global/chv.php" class="spriteglobal sprite-chv Chilevisi&oacute;n"></a>';
$cards[2]='<a href="/global/atv.php" class="spriteglobal sprite-atv ATV"></a><a href="/global/global.php" class="spriteglobal sprite-global Global"></a><a href="/global/panamericana.php" class="spriteglobal sprite-panamericana Panamericana"></a><a href="/global/frecuencialatina.php" class="spriteglobal sprite-frecuencialatina Frecuencia Latina"></a><br><a href="/global/tvperu.php" class="spriteglobal sprite-tvperu TV Per&uacute;"></a><a href="/global/americap.php" class="spriteglobal sprite-americap Am&eacute;rica Peru"></a>';
$cards[3]='<a href="/global/gamatv.php" class="spriteglobal sprite-gamatv Gama TV"></a><a href="/global/ectv.php" class="spriteglobal sprite-ectv ECTV"></a><a href="/global/uno.php" class="spriteglobal sprite-uno Uno"></a><a href="/global/ecuavisa.php" class="spriteglobal sprite-ecuavisa Ecuavisa"></a>';
$cards[4]='<a href="/global/caracol.php" class="spriteglobal sprite-caracol Caracol"></a><a href="/global/rcn.php" class="spriteglobal sprite-rcn RCN"></a><a href="/global/ntn24.php" class="spriteglobal sprite-ntn24 NTN24"></a><a href="/global/scolombia.php" class="spriteglobal sprite-scolombia Se&ntilde;al Colombia"></a><a href="/global/telemedellin.php" class="spriteglobal sprite-telemedellin Telemedellin"></a>';
$cards[5]='<a href="/global/vtv.php" class="spriteglobal sprite-vtv VTV"></a><a href="/global/globovision.php" class="spriteglobal sprite-globovision Globovision"></a><a href="/global/venevision.php" class="spriteglobal sprite-venevision Globovision"></a>';
$cards[6]='<a href="/global/milenio.php" class="spriteglobal sprite-milenio Milenio"></a><a href="/global/teleformula.php" class="spriteglobal sprite-teleformula Telef&oacute;rmula"></a><a href="/global/azteca7.php" class="spriteglobal sprite-azteca7 Azteca 7"></a><a href="/global/azteca13.php" class="spriteglobal sprite-azteca13 Azteca 13"></a><a href="/global/telemundo.php" class="spriteglobal sprite-telemundo Telemundo"></a><a href="/global/univision.php" class="spriteglobal sprite-univision Univision"></a>';
$cards[7]='<a href="/global/antena3.php" class="spriteglobal sprite-antena3 Antena 3"></a><a href="/global/cuatro.php" class="spriteglobal sprite-cuatro Cuatro"></a><a href="/global/telecinco.php" class="spriteglobal sprite-telecinco Telecinco"></a><a href="/global/lasexta.php" class="spriteglobal sprite-lasexta La Sexta"></a><br><a href="/global/tve1.php" class="spriteglobal sprite-la1 TVE 1"></a><a href="/global/tve2.php" class="spriteglobal sprite-la2 TVE 2"></a><a href="/global/tdp.php" class="spriteglobal sprite-tdp Teledeporte"></a><a href="/global/24h.php" class="spriteglobal sprite-24h 24h"></a><br><a href="/global/tvg.php" class="spriteglobal sprite-tvg TVG"></a><a href="/global/tvg2.php" class="spriteglobal sprite-tvg2 TVG2"></a>';
$cards[8]='<a href="/global/dw.php" class="spriteglobal sprite-dw DW"></a><a href="/global/euronews.php" class="spriteglobal sprite-euronews Euronews"></a><a href="/global/bbc.php" class="spriteglobal sprite-bbc BBC World News"></a>';

$model=[
'activa'=>1,
'titulo'=>'Global | Colgado',
'descripcion'=>'Colgado.TV es el mejor sitio web para ver TV y escuchar radio por internet en vivo las 24hs online, gratis y sin l&iacute;mites.',
'cards' => $cards];

include_once'../controller/prepare.php';?>