<?php
$activa=2; 
$titulo='Radios | Colgado';
$luces="no";
$ad="no";
$programacion='';
$descripcion='Colgado.TV es el mejor sitio web para ver TV y escuchar radio por internet en vivo las 24hs online, gratis y sin l&iacute;mites.';
$cards[1]='<a href="/radios/la100/"class="spriteradio sprite-la100 La 100"></a><a href="/radios/pop/"class="spriteradio sprite-pop Pop"></a>&nbsp;<a href="/radios/metro/"class="spriteradio sprite-metro Metro"></a>&nbsp;<a href="/radios/disney/"class="spriteradio sprite-disney Disney"></a>&nbsp;<a href="/radios/los40/"class="spriteradio sprite-los40 Los 40"></a><br><a href="/radios/rocknpop/"class="spriteradio sprite-rocknpop Rock & Pop"></a>&nbsp;<a href="/radios/aspen/"class="spriteradio sprite-aspen Aspen"></a>&nbsp;<a href="/radios/vale/"class="spriteradio sprite-vale Vale"></a>&nbsp;<a href="/radios/one/"class="spriteradio sprite-one ONE"></a><br><a href="/radios/nacionalrock/"class="spriteradio sprite-nacionalrock Nacional Rock"></a>&nbsp;<a href="/radios/rqp/"class="spriteradio sprite-rqp RQP"></a>&nbsp;<a href="/radios/latina/"class="spriteradio sprite-latina Latina"></a><br><a href="/radios/radiox/"class="spriteradio sprite-radiox Radio X"></a>&nbsp;<a href="/radios/mega/"class="spriteradio sprite-mega Mega"></a>&nbsp;<a href="/radios/vorterix/"class="spriteradio sprite-vorterix Vorterix"></a>&nbsp;<a href="/radios/milenium/"class="spriteradio sprite-milenium Millenium"></a><br><a href="/radios/blue/"class="spriteradio sprite-blue FM Blue"></a>&nbsp;<a href="/radios/espn/"class="spriteradio sprite-espn Espn"></a>&nbsp;<a href="/radios/pasion/"class="spriteradio sprite-fmpasion FM Pasi&oacute;n"></a>';
$cards[2]='<a href="/radios/mitre/"class="spriteradio sprite-mitre Mitre"></a>&nbsp;<a href="/radios/radio10/"class="spriteradio sprite-radio10 Radio 10"></a>&nbsp;<a href="/radios/lared/"class="spriteradio sprite-lared La Red"></a>&nbsp;<a href="/radios/continental/"class="spriteradio sprite-continental Continental"></a><br><a href="/radios/radionacional/"class="spriteradio sprite-radionacional Radio Nacional"></a>&nbsp;<a href="/radios/delplata/"class="spriteradio sprite-delplata Del Plata"></a>&nbsp;<a href="/radios/am750/"class="spriteradio sprite-am750 AM 750"></a><br><a href="/radios/rivadavia/"class="spriteradio sprite-rivadavia Rivadavia"></a>&nbsp;<a href="/radios/radio9/"class="spriteradio sprite-radio9 Radio 9"></a>&nbsp;<a href="/radios/america1190/"class="spriteradio sprite-america1190 Am&eacute;rica 1190"></a>&nbsp;<a href="/radios/cooperativa/"class="spriteradio sprite-cooperativa Cooperativa"></a>';
$cards[3]='<a href="/radios/cadena3/"class="spriteradio sprite-cadena3 Cadena 3"></a>&nbsp;<a href="/radios/delsol/"class="spriteradio sprite-delsol FM del Sol"></a>&nbsp;<a href="/radios/brava/"class="spriteradio sprite-brava Brava"></a><br><a href="/radios/vida/"class="spriteradio sprite-vida FM Vida"></a>&nbsp;<a href="/radios/la8/"class="spriteradio sprite-la8 La 8"></a><br><a href="/radios/la99/"class="spriteradio sprite-la99 La 99.1"></a>&nbsp;<a href="/radios/red92/"class="spriteradio sprite-red92 Red 92"></a>&nbsp;<a href="/radios/laredonda/"class="spriteradio sprite-laredonda La Redonda"></a><br><a href="/radios/cielo/"class="spriteradio sprite-cielo FM Cielo"></a>&nbsp;<a href="/radios/coolradio/"class="spriteradio sprite-coolradio Cool Radio"></a><br><a href="/radios/lu24/"class="spriteradio sprite-lu24 LU24 Radio Tres Arroyos"></a>&nbsp;<a href="/radios/fm105/"class="spriteradio sprite-fm105 FM 105"></a><a href="/radios/ilusiones/"class="spriteradio sprite-ilusiones Ilusiones"></a>';
include_once'../controller/prepare.php';
?>