<?php
$cards[1]='<a href="/radios/la100.php"class="spriteradio sprite-la100 La 100"></a><a href="/radios/pop.php"class="spriteradio sprite-pop Pop"></a>&nbsp;<a href="/radios/metro.php"class="spriteradio sprite-metro Metro"></a>&nbsp;<a href="/radios/disney.php"class="spriteradio sprite-disney Disney"></a>&nbsp;<a href="/radios/los40.php"class="spriteradio sprite-los40 Los 40"></a><br><a href="/radios/rocknpop.php"class="spriteradio sprite-rocknpop Rock & Pop"></a>&nbsp;<a href="/radios/aspen.php"class="spriteradio sprite-aspen Aspen"></a>&nbsp;<a href="/radios/vale.php"class="spriteradio sprite-vale Vale"></a>&nbsp;<a href="/radios/one.php"class="spriteradio sprite-one ONE"></a><br><a href="/radios/nacionalrock.php"class="spriteradio sprite-nacionalrock Nacional Rock"></a>&nbsp;<a href="/radios/rqp.php"class="spriteradio sprite-rqp RQP"></a>&nbsp;<a href="/radios/latina.php"class="spriteradio sprite-latina Latina"></a><br><a href="/radios/radiox.php"class="spriteradio sprite-radiox Radio X"></a>&nbsp;<a href="/radios/mega.php"class="spriteradio sprite-mega Mega"></a>&nbsp;<a href="/radios/vorterix.php"class="spriteradio sprite-vorterix Vorterix"></a>&nbsp;<a href="/radios/milenium.php"class="spriteradio sprite-milenium Millenium"></a><br><a href="/radios/blue.php"class="spriteradio sprite-blue FM Blue"></a>&nbsp;<a href="/radios/espn.php"class="spriteradio sprite-espn Espn"></a>&nbsp;<a href="/radios/pasion.php"class="spriteradio sprite-fmpasion FM Pasi&oacute;n"></a>';
$cards[2]='<a href="/radios/mitre.php"class="spriteradio sprite-mitre Mitre"></a>&nbsp;<a href="/radios/radio10.php"class="spriteradio sprite-radio10 Radio 10"></a>&nbsp;<a href="/radios/lared.php"class="spriteradio sprite-lared La Red"></a>&nbsp;<a href="/radios/continental.php"class="spriteradio sprite-continental Continental"></a><br><a href="/radios/radionacional.php"class="spriteradio sprite-radionacional Radio Nacional"></a>&nbsp;<a href="/radios/delplata.php"class="spriteradio sprite-delplata Del Plata"></a>&nbsp;<a href="/radios/am750.php"class="spriteradio sprite-am750 AM 750"></a><br><a href="/radios/rivadavia.php"class="spriteradio sprite-rivadavia Rivadavia"></a>&nbsp;<a href="/radios/radio9.php"class="spriteradio sprite-radio9 Radio 9"></a>&nbsp;<a href="/radios/america1190.php"class="spriteradio sprite-america1190 Am&eacute;rica 1190"></a>&nbsp;<a href="/radios/cooperativa.php"class="spriteradio sprite-cooperativa Cooperativa"></a>';
$cards[3]='<a href="/radios/cadena3.php"class="spriteradio sprite-cadena3 Cadena 3"></a>&nbsp;<a href="/radios/delsol.php"class="spriteradio sprite-delsol FM del Sol"></a>&nbsp;<a href="/radios/brava.php"class="spriteradio sprite-brava Brava"></a><br><a href="/radios/vida.php"class="spriteradio sprite-vida FM Vida"></a>&nbsp;<a href="/radios/la8.php"class="spriteradio sprite-la8 La 8"></a><br><a href="/radios/la99.php"class="spriteradio sprite-la99 La 99.1"></a>&nbsp;<a href="/radios/red92.php"class="spriteradio sprite-red92 Red 92"></a>&nbsp;<a href="/radios/laredonda.php"class="spriteradio sprite-laredonda La Redonda"></a><br><a href="/radios/cielo.php"class="spriteradio sprite-cielo FM Cielo"></a>&nbsp;<a href="/radios/coolradio.php"class="spriteradio sprite-coolradio Cool Radio"></a><br><a href="/radios/lu24.php"class="spriteradio sprite-lu24 LU24 Radio Tres Arroyos"></a>&nbsp;<a href="/radios/fm105.php"class="spriteradio sprite-fm105 FM 105"></a><a href="/radios/ilusiones.php"class="spriteradio sprite-ilusiones Ilusiones"></a>';

$model=[
'activa'=>2,
'titulo'=>'Radios | Colgado',
'descripcion'=>'Colgado.TV es el mejor sitio web para ver TV y escuchar radio por internet en vivo las 24hs online, gratis y sin l&iacute;mites.',
'cards' => $cards];

include_once'../controller/prepare.php';
?>