<?php
if (isset($index)){

$cards[1]='<a href="/tv/telefe.php" class="spritetv sprite-telefe"></a>&nbsp;<a href="/tv/eltrece.php" class="spritetv sprite-eltrece"></a>&nbsp;<a href="/tv/america.php" class="spritetv sprite-america"></a><br><a href="/tv/tvpublica.php" class="spritetv sprite-tvp"></a>&nbsp;<a href="/tv/canal9.php" class="spritetv sprite-canal9"></a>';
$cards[2]='<a href="/tv/tn.php" class="spritetv sprite-tn"></a>&nbsp;<a href="/tv/c5n.php" class="spritetv sprite-c5n"></a>&nbsp;<a href="/tv/america24.php" class="spritetv sprite-a24"></a><a href="/tv/canal26.php" class="spritetv sprite-canal26"></a><br><a href="/tv/telesur.php" class="spritetv sprite-telesur"></a>&nbsp;<a href="/tv/rt.php" class="spritetv sprite-rt"></a><br>';
$cards[3]='<a href="/tv/tycsports.php" class="spritetv sprite-tycsports"></a>&nbsp;<a href="/tv/dxtv.php" class="spritetv sprite-dxtv"></a>&nbsp;<a href="/tv/americasports.php" class="spritetv sprite-americasports2"></a>&nbsp;<a href="/tv/garage.php" class="spritetv sprite-garage "></a>&nbsp;<a href="/tv/directvsports.php" class="spritetv sprite-directvsports DirecTV Sports"></a><br><a href="/tv/espn.php" class="spritetv sprite-espntv ESPN"></a>&nbsp;<a href="/tv/espn2.php" class="spritetv sprite-espn2 ESPN2"></a><br><a href="/tv/foxsports.php" class="spritetv sprite-foxsports Fox Sports"></a>&nbsp;<a href="/tv/foxsports2.php" class="spritetv sprite-foxsports2 Fox Sports 2"></a>';
$cards[4]='<a href="/tv/tec.php" class="spritetv sprite-tec Tecn&oacute;polis TV"></a>&nbsp;<a href="/tv/encuentro.php" class="spritetv sprite-encuentro Encuentro"></a><br><a href="/tv/history.php" class="spritetv sprite-history History"></a>&nbsp;<a href="/tv/discovery.php" class="spritetv sprite-discovery Discovery"></a>&nbsp;<a href="/tv/natgeo.php" class="spritetv sprite-natgeo Nat Geo"></a><br><a href="/tv/id.php" class="spritetv sprite-id Investigation Discovery"></a>&nbsp;<a href="/tv/trutv.php" class="spritetv sprite-trutv Trutv"></a><br><a href="/tv/tlc.php" class="spritetv sprite-tlc TLC"></a>&nbsp;<a href="/tv/hyh.php" class="spritetv sprite-hyh h&#38;h"></a>&nbsp;<a href="/tv/animalplanet.php" class="spritetv sprite-animalplanet Animal Planet"></a>';
$cards[5]='<a href="/tv/magazine.php" class="spritetv sprite-magazine Magazine"></a>&nbsp;&nbsp;<a href="/tv/360.php" class="spritetv sprite-360tv 360TV"></a>&nbsp;&nbsp;<a href="/tv/construirtv.php" class="spritetv sprite-construirtv Construir TV"></a>&nbsp;<a href="/tv/tvuniversidad.php" class="spritetv sprite-tvuniversidad TV Universidad"></a><br><a href="/tv/acuamayor.php" class="spritetv sprite-acuamayor Acua Mayor"></a>&nbsp;<a href="/tv/qm.php" class="spritetv sprite-qm QM La Plata"></a>&nbsp;<a href="/tv/argentinisima.php" class="spritetv sprite-argentinisima Argentin&iacute;sima"></a>&nbsp;<a href="/tv/rural.php" class="spritetv sprite-rural Canal Rural"></a>&nbsp;<a href="/tv/acuafederal.php" class="spritetv sprite-acuafederal Acua Federal"></a>';
$cards[6]='<a href="/tv/mtv.php" class="spritetv sprite-mtv MTV"></a>&nbsp;<a href="/tv/vh1.php" class="spritetv sprite-vh1 VH1"></a>&nbsp;<a href="/tv/vevo.php" class="spritetv sprite-vevo VEVO"></a>&nbsp;<a href="/tv/onetv.php" class="spritetv sprite-onetv One Tv"></a>&nbsp;<a href="/tv/rocknpop.php" class="spritetv sprite-rocknpoptv Rock & Pop Se Ve"></a>';
$cards[7]='<a href="/tv/pakapaka.php" class="spritetv sprite-pakapaka Paka Paka"></a>&nbsp;<a href="/tv/tateti.php" class="spritetv sprite-tateti tateti"></a>&nbsp;<a href="/tv/cartoon.php" class="spritetv sprite-cartoon Cartoon Network"></a><br><a href="/tv/nick.php" class="spritetv sprite-nick Nick"></a>&nbsp;<a href="/tv/discoverykids.php" class="spritetv sprite-discoverykids Discovery Kids"></a>&nbsp;<a href="/tv/disney.php" class="spritetv sprite-disneychannel Disney Channel"></a>&nbsp;<a href="/tv/disneyjunior.php" class="spritetv sprite-disneyjunior Disney Junior"></a>&nbsp;<a href="/tv/disneyxd.php" class="spritetv sprite-disneyxd Disney XD"></a>';
$cards[8]='<a href="/tv/fox.php" class="spritetv sprite-fox FOX"></a>&nbsp;<a href="/tv/warner.php" class="spritetv sprite-warner Warner"></a>&nbsp;<a href="/tv/fx.php" class="spritetv sprite-fx FX"></a><br><a href="/tv/ftv.php" class="spritetv sprite-ftv FTV"></a>&nbsp;<a href="/tv/foxlife.php" class="spritetv sprite-foxlife Fox Life"></a>&nbsp;<a href="/tv/e!.php" class="spritetv sprite-e! E!"></a><br><a href="/tv/universal.php" class="spritetv sprite-universal Universal"></a>&nbsp;<a href="/tv/axn.php" class="spritetv sprite-axn AXN"></a>&nbsp;<a href="/tv/sony.php" class="spritetv sprite-sony Sony"></a><br><a href="/tv/tbs.php" class="spritetv sprite-tbs TBS Veryfunny"></a>&nbsp;<a href="/tv/comedycentral.php" class="spritetv sprite-comedycentral Comedy Central"></a>&nbsp;<a href="/tv/syfy.php" class="spritetv sprite-syfy Syfy"></a><br><a href="/tv/gourmet.php" class="spritetv sprite-gourmet El Gourmet"></a>&nbsp;<a href="/tv/ae.php" class="spritetv sprite-ae A&#38;E"></a>&nbsp;<a href="/tv/infinito.php" class="spritetv sprite-infinito Infinito"></a><br><a href="/tv/glitz.php" class="spritetv sprite-glitz Glitz"></a>&nbsp;<a href="/tv/tlnovelas.php" class="spritetv sprite-tlnovelas Tlnovelas"></a>&nbsp;<a href="/tv/casaclub.php" class="spritetv sprite-casaclub Casa Club"></a>';
$cards[9]='<a href="/tv/tnt.php" class="spritetv sprite-tnt TNT"></a>&nbsp;&nbsp;<a href="/tv/space.php" class="spritetv sprite-space Space"></a>&nbsp;<a href="/tv/cinecanal.php" class="spritetv sprite-cinecanal Cinecanal"></a><br><a href="/tv/studiouniversal.php" class="spritetv sprite-studiouniversal Studio Universal"></a>&nbsp;&nbsp;<a href="/tv/filmzone.php" class="spritetv sprite-filmzone Film Zone"></a>&nbsp;&nbsp;<a href="/tv/isat.php" class="spritetv sprite-isat I-Sat"></a><br><a href="/tv/cinemax.php" class="spritetv sprite-cinemax Cinemax"></a>&nbsp;&nbsp;<a href="/tv/amc.php" class="spritetv sprite-amc AMC"></a>&nbsp;&nbsp;<br><a href="/tv/tcm.php" class="spritetv sprite-tcm TCM"></a>&nbsp;&nbsp;<a href="/tv/golden.php" class="spritetv sprite-golden Golden Edge"></a>&nbsp;&nbsp;<a href="/tv/hbo.php" class="spritetv sprite-hbo HBO"></a>&nbsp;<a href="/tv/hboplus.php" class="spritetv sprite-hboplus HBO Plus"></a>&nbsp;&nbsp;';

$model=[
'activa'=>0,
'titulo'=>'Colgado del Cable',



'descripcion'=>'Colgado del Cable es el mejor sitio web para ver TV y escuchar radio por internet en vivo las 24hs online, gratis y sin l&iacute;mites.',
'cards'=>$cards ];
}
else{
	header('Location: /');
}?>
